const state={role:null,token:localStorage.getItem("wingo_student_token"),adminKey:sessionStorage.getItem("wingo_admin_key"),students:[]};
const $=id=>document.getElementById(id);
const views=["authView","studentView","teacherView"];
const show=id=>{document.body.dataset.view=id;views.forEach(view=>$(view).classList.toggle("hidden",view!==id))};
const fmtDate=value=>value?new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value)):"Sem registro";
const safe=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
async function api(path,options={}){const response=await fetch(path,options);if(!response.ok){let message="Não foi possível carregar os dados.";try{message=(await response.json()).detail||message}catch{}throw new Error(message)}return response.json()}
function online(ok=true){$("connectionStatus").classList.toggle("online",ok);$("connectionStatus").innerHTML=`<i></i> ${ok?"Sistema online":"Atenção necessária"}`}
document.querySelectorAll(".role-tab").forEach(tab=>tab.addEventListener("click",()=>{document.querySelectorAll(".role-tab").forEach(item=>item.classList.toggle("active",item===tab));$("studentLogin").classList.toggle("hidden",tab.dataset.role!=="student");$("teacherLogin").classList.toggle("hidden",tab.dataset.role!=="teacher");$("authError").textContent=""}));
$("studentLogin").addEventListener("submit",async event=>{event.preventDefault();$("authError").textContent="";try{const result=await api("/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:$("studentEmail").value,password:$("studentPassword").value})});state.token=result.access_token;localStorage.setItem("wingo_student_token",state.token);await loadStudent()}catch(error){$("authError").textContent=error.message}});
$("teacherLogin").addEventListener("submit",async event=>{event.preventDefault();state.adminKey=$("adminKey").value;sessionStorage.setItem("wingo_admin_key",state.adminKey);try{await loadTeacher()}catch(error){$("authError").textContent=error.message;sessionStorage.removeItem("wingo_admin_key")}});
$("logoutButton").addEventListener("click",()=>{localStorage.removeItem("wingo_student_token");sessionStorage.removeItem("wingo_admin_key");state.token=null;state.adminKey=null;$("logoutButton").classList.add("hidden");show("authView")});
function stat(label,value,accent=false){return `<div class="stat-card ${accent?"accent":""}"><span>${safe(label)}</span><strong>${safe(value)}</strong></div>`}
async function loadStudent(){const data=await api("/dashboard/api/student",{headers:{Authorization:`Bearer ${state.token}`}});state.role="student";show("studentView");$("logoutButton").classList.remove("hidden");$("studentName").textContent=data.name||"aluno";$("studentLevel").textContent=data.level||"Em avaliação";$("studentSubtitle").textContent=data.learning_goal?`Objetivo: ${data.learning_goal}`:"Aqui está o seu próximo passo.";$("studentStats").innerHTML=stat("XP acumulado",data.xp,true)+stat("Sequência",`${data.streak_days} dias`)+stat("Aulas concluídas",data.completed_lessons)+stat("Minutos praticados",data.engagement_minutes);$("currentLesson").textContent=data.current_lesson;$("lessonStage").textContent=`Etapa atual: ${data.lesson_stage_label}`;$("lessonProgress").style.width=`${data.lesson_progress_percent}%`;$("studentSchedule").textContent=data.schedule||"Agenda não definida";$("learningMode").textContent=data.learning_mode_label;$("learningRecords").innerHTML=data.recent_learning_records.length?data.recent_learning_records.map(record=>`<div class="record"><strong>${safe(record.topic||"Prática recente")}</strong><p>${safe(record.corrected_text||record.explanation||record.original_text)}</p></div>`).join(""):`<div class="empty">Seus próximos aprendizados aparecerão aqui.</div>`;online(true)}
function renderStudents(filter=""){const term=filter.toLowerCase();const rows=state.students.filter(student=>`${student.name} ${student.phone} ${student.level}`.toLowerCase().includes(term));$("studentsTable").innerHTML=rows.length?rows.map(student=>`<tr><td><strong>${safe(student.name||"Sem nome")}</strong><small>${safe(student.phone)}</small></td><td>${safe(student.level)}</td><td><span class="mode-chip">${safe(student.learning_mode_label)}</span></td><td><strong>${safe(student.current_lesson)}</strong><small>${safe(student.lesson_stage_label)}</small></td><td>${safe(student.xp)}</td><td>${safe(fmtDate(student.last_activity))}</td></tr>`).join(""):`<tr><td colspan="6"><div class="empty">Nenhum aluno encontrado.</div></td></tr>`}
async function loadTeacher(){const headers={"X-Admin-Key":state.adminKey};const [cohort,operations]=await Promise.all([api("/dashboard/api/teacher",{headers}),api("/dashboard/api/operations",{headers})]);state.role="teacher";state.students=cohort.students;show("teacherView");$("logoutButton").classList.remove("hidden");$("teacherStats").innerHTML=stat("Alunos",cohort.summary.total_students,true)+stat("Ativos em 7 dias",cohort.summary.active_students)+stat("Aulas concluídas",cohort.summary.completed_lessons)+stat("XP da turma",cohort.summary.total_xp);renderStudents();const health=operations.health;$("healthBadge").textContent=health.status;$("healthBadge").classList.toggle("degraded",health.status!=="ok");$("healthMetrics").innerHTML=[["Erros / 15 min",health.errors_last_15_minutes],["Entregas falhas",health.failed_deliveries_last_15_minutes],["Entradas presas",health.stuck_inbound_messages],["Saídas presas",health.stuck_outbound_deliveries]].map(([label,value])=>`<div class="health-item"><strong>${safe(value)}</strong><span>${safe(label)}</span></div>`).join("");$("transitionList").innerHTML=operations.transitions.length?operations.transitions.map(item=>`<div class="transition"><strong>${safe(item.previous_state)} → ${safe(item.next_state)}</strong><p>${safe(item.flow||"fluxo")} · aluno ${safe(item.student_id)}</p><time>${safe(fmtDate(item.created_at))}</time></div>`).join(""):`<div class="empty">Nenhuma transição registrada.</div>`;online(health.status==="ok")}
$("studentSearch").addEventListener("input",event=>renderStudents(event.target.value));$("refreshTeacher").addEventListener("click",()=>loadTeacher().catch(error=>alert(error.message)));
async function boot(){try{const health=await api("/ops/health");online(health.status==="ok")}catch{online(false)}try{if(state.token)return await loadStudent();if(state.adminKey)return await loadTeacher()}catch{localStorage.removeItem("wingo_student_token");sessionStorage.removeItem("wingo_admin_key")}show("authView")}
boot();
